tasks:
  - name: client-side
    command: >
      cd client &&
      yarn start

  - name: server-side
    command: >
      cd server &&
      npm install -g nodemon &&
      yarn start

vscode:
  extensions:
    - dracula-theme.theme-dracula
    - file-icons.file-icons

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public

  -port: 8081
    onOpen: open-browser
    visibility: public