tasks:
  - name: client-side
    init: cd client && yarn install && cd ../
    command: >
      cd client &&
      yarn start

  - name: server-side
    init: cd server && yarn install && cd ../
    command: >
      cd server &&
      npm install -g nodemon &&
      yarn start

vscode:
  extensions:
    - dracula-theme.theme-dracula
    - file-icons.file-icons

ports:
  - port: 3000
    onOpen: notify
    visibility: public

  - port: 8081
    onOpen: notify
    visibility: public