tasks:
  - init: npm install -g nodemon
    command: cd client
    
  - before: npm install -g nodemon



# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8081
    onOpen: open-preview
