tasks:
  - before: npm install -g nodemon
    init: npm install
    command: cd client
  # - name: Database
  #   init: sh ./scripts/seed-database.sh
  #   command: npm start-db
  #   env:
  #     DB_HOST: localhost:3306
  #     DB_USER: readOnlyUser